language: python

python:
  - 3.6

services:
  - docker

install:
  # Adds dependencies:
  - pip install docker-image-size-limit
  # Building image itself:
  - docker build -t caddy-gen:latest .
  - docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro --name caddy-gen caddy-gen
  - sleep 1

script:
  - docker ps | grep -q caddy-gen # there should be a docker process
  - http_code=$(curl -s -w "%{http_code}" 127.0.0.1 | tail -n 1)
  - test $http_code -eq 308
  - disl caddy-gen:latest 90MB

notifications:
  email:
    on_success: never
    on_failure: change
